#!/bin/bash

out=$(sudo -u solr /opt/solr/bin/solr status 2>/dev/null|grep -E '^No|^Found|^Solr|^\s'|sed 's/["},]//g'|sed 's/:/: /g')
readarray <<<$out
for (( i=0; i<${#MAPFILE[@]}; i++ ))
do
  line=$(echo "${MAPFILE[$i]}"|sed 's/\\n//g'|awk '{$1=$1};1')
# todo: In Python 3.7 insertion will be default and the commented code will produce nicer output.
# See https://mail.python.org/pipermail/python-dev/2017-December/151283.html
#  if [[ ${i} -eq 0 ]]; then
#    arg="output.nodes"
#  elif [[ ${i} -eq 1 ]]; then
#    arg="output.process"
#  else
#    arg="output.${i}"
#  fi
  action-set "output.${i}"="${line}"
done
