#!/bin/bash

port=$(action-get port)
all=$(action-get all)

if [ "${port:-0}" -gt "0" ]; then
  port="-p ${port}"
else
  port=""
fi

if [ "${all:-False}" = True ]; then
  all="-all"
else
  all=""
fi


command="sudo -u solr /opt/solr/bin/solr stop ${port}${all}"
out=$($command  2>/dev/null)
readarray <<<$out

if [[ $? -ne 0 ]]; then
  action-fail "output"="${MAPFILE[0]}"
else
#for (( i=0; i<${#MAPFILE[@]}; i++ ))
#  do
#    line=$(echo "${MAPFILE[$i]}"|sed 's/\\n//g'|awk '{$1=$1};1')
#    action-set "output.${i}"="${line}"
#  done
  action-set "result.output"="${MAPFILE[0]}"
fi
